Minor change to make --inputs-file actually work
Without it the gem throws an error:

`.rvm/gems/ruby-2.1.10/gems/timing_attack-0.7.0/exe/timing_attack:56:in `block (2 levels) in opt_parser': undefined local variable or method `filename' for #<TimingAttackCli:0x000000014a6630> (NameError)`